### ISSUE TITLE
`Generator.createHexagonGrid` doc comment / functionality missmatch

### ISSUE THREAD

**Issue by mgrider** [fananek/hex-grid#10]
The comment for the `radius` parameter says `0` will produce a single hexagon, but a value of `0` actually throws an `InvalidArgumentError`.

I also think the doc comments for `GridShape` cases could use expanding, maybe with some examples. For instance, the `.hexagon` case just says "radius", but I think it's more common to talk about regular hex grids by "side length" (which is of course "radius + 1"). At least I understand the meaning of radius, but I don't really understand what the `.triangle`'s "side size" parameter means, because it seems to produce a triangle with a side-size of one more than that. (For consistency?) Maybe the triangle parameter is actually a bug, I don't really know.

**Comment by fananek** [comment]
These are very valid points. Thank you. 

The first one is a bug. The other two are more about a consistent and intuitive approach.
All of them have in release `0.4.8`. **Please note this is a breaking change!**

**New behavior:**
Grid generator now accepts `side length` argument for both hexagon and triangle-shaped grids. This side length works as you would expect in the real world.

**Examples:**
- hexagon-shaped grid of **side length equal to 1** produces a grid of exactly **1 cell**.
- hexagon-shaped grid of **side length equal to 2** produces a grid of **7 cells**.
- hexagon-shaped grid of **side length equal to 3** produces a grid of **19 cells**.
- triangle-shaped grid of **side length equal to 1** produces a grid of exactly **1 cell**.
- triangle-shaped grid of **side length equal to 2** produces a grid of **3 cells**.
- triangle-shaped grid of **side length equal to 3** produces a grid of **6 cells**.
- triangle-shaped grid of **side length equal to 4** produces a grid of **10 cells**.

**Comment by mgrider** [comment]
This is great, thank you!
