### ISSUE TITLE
issues with rectangular generator

### ISSUE THREAD

**Issue by mgrider** [fananek/hex-grid#13]
**Describe the bug**
As mentioned in #12, when generating cells using the `.rectangle` `GridShape`, the resulting grid appears rotated from what is expected in 3 out of 4 possible combinations of `Orientation` and `OffsetLayout`.

**To Reproduce**
It is probably easiest to reproduce this behavior by drawing/visualizing the resulting grid. Here are some screenshots generated using the [SKHexGrid](https://github.com/mgrider/SKHexGrid) project. The coordinates shown are Axial.

Orientation: `.pointyOnTop`, OffsetLayout: `.even`
<img width="351" alt="Screen Shot 2022-08-10 at 3 15 10 PM" src="https://user-images.githubusercontent.com/604867/184011826-6c932d5b-2a90-4249-a5e3-a9627a4ca8aa.png">

Orientation: `.pointyOnTop`, OffsetLayout: `.odd`
<img width="346" alt="Screen Shot 2022-08-10 at 3 17 55 PM" src="https://user-images.githubusercontent.com/604867/184011933-09854938-1628-4f16-80f6-836101ed3465.png">

Orientation: `.flatOnTop`, OffsetLayout: `.even`
<img width="339" alt="Screen Shot 2022-08-10 at 3 18 36 PM" src="https://user-images.githubusercontent.com/604867/184012040-508f4fa3-c776-464d-8872-0e3a5a8f12fa.png">

Orientation: `.flatOnTop`, OffsetLayout: `.odd`
<img width="349" alt="Screen Shot 2022-08-10 at 3 19 06 PM" src="https://user-images.githubusercontent.com/604867/184012123-0eb446ae-0cd1-4a47-86d2-76acb2d805f5.png">

**Expected behavior**
You can see from the screenshots that only the `.flatOnTop`, `.even` layout appears to be correct.

**Comment by fananek** [comment]
Rectangular generator has been fixed in version 0.4.10.

**Comment by fananek** [comment]
During implementation of this fix I realized that convertor and generator might need some redesign. At this moment rectangular generator produces rectangular grids for all four possible configurations. But I'm not fully satisfied. Let's keep track in issue no. #14.

**Comment by mgrider** [comment]
Thank you for working on this!
