### ISSUE TITLE
Feature request: Get the pixel width/height of the grid

### ISSUE THREAD

**Issue by mattpolzin** [fananek/hex-grid#3]

**Comment by fananek** [comment]
I do agree. Possibility to get whole grid pixel dimensions make sense. I’ll add this feature.

**Comment by fananek** [comment]
Available in release 0.3.1. - Grid pixel dimensions are now available as public (read-only) properties. It's being updated via property observer.

**Comment by mattpolzin** [comment]
Woo! 🎉
